
[project]
name = "ideas-toolbox-suite2p"
description = "IDEAS Suite2p Toolkit"
requires-python = "==3.10.12"
classifiers = [
    "Programming Language :: Python :: 3"
]
dependencies = [
    "ideas-python[analysis]==1.1.1",
    "pynwb==2.8.1",
    "hdmf==3.14.0",
    "dandi==0.63.0",
    "numpy==1.26.4",
    "scikit-learn==1.4.2",
    "scipy==1.13.0",
    "suite2p@git+https://@github.com/inscopix/isxSuite2p.git@366988377711617401765a30a2b20a91f160be5b",
    "imageio==2.33.0",
    "imageio-ffmpeg==0.4.7",
    "pytest==7.4.2",
    "isx==2.1.0",
]

dynamic = ["version"]

[tool.pytest.ini_options]
pythonpath = [
  "."
]

[tool.black]
line-length = 79

[tool.interrogate]
fail-under = 100
exclude = ["setup.py", "docs", "build", "tests"]
ignore-init-method = true
ignore-init-module = true
ignore-magic = true
ignore-semiprivate = true
ignore-private = true
ignore-property-decorators = true
ignore-module = true
ignore-nested-functions = true
ignore-nested-classes = true
ignore-setters = false
ignore-regex = ["^get$", "^mock_.*", ".*BaseClass.*"]
color = true